services:

  web:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
      args: #variables en DF para el build de la imagen
        - USUARIO=carmen
        - PASSWORD=1234
    container_name: ctPortfolioNginx
    ports:
    - "8820:80"