services:
  web:
    build:
      context: /home/carmen/devops/Docker/Caronte
      dockerfile: ./dockerfiles/base/ubbase
      #args:
      #- USUARIO=alfonso
    container_name: ctpbase
    environment:
      - USUARIO=alfonso 
      - PASSWORD=pswalfonso
    volumes:
      - ./logs:/root/logs